### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by ToddyG** [NullArray/Keylogger#9]
Traceback (most recent call last):
  File "C:\Python27\logger.py", line 1, in <module>
    import pythoncom, pyHook
  File "C:\Python27\lib\site-packages\pyHook\__init__.py", line 1, in <module>
    from HookManager import *
  File "C:\Python27\lib\site-packages\pyHook\HookManager.py", line 1, in <module>
    import cpyHook
  File "C:\Python27\lib\site-packages\pyHook\cpyHook.py", line 7, in <module>
    import _cpyHook
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by NullArray** [comment]
This project is outdated. I am currently working on a complete rewrite. With more features and a different command and control mechanism.

For more information please reference the following ticket; https://github.com/NullArray/Keylogger/issues/8 to be taken to the post in question.
